<%@page contentType="text/html;charset=utf-8"%>
<%
    request.setAttribute("base", request.getContextPath());	
%>

         <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta http-equiv="Cache-Control" content="no-siteapp" />
            <meta name="renderer" content="webkit">
            <meta name="description" content="">
            <link rel="alternate icon" type="image/png" href="http://s.amazeui.org/assets/2.x/i/favicon.png">
            <link rel="apple-touch-icon-precomposed" href="http://s.amazeui.org/assets/2.x/i/app-icon72x72@2x.png">
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="black">
            <link rel="stylesheet" href="http://s.amazeui.org/assets/2.x/css/amazeui.min.css?v=ibj1fy0x">
            <link rel="stylesheet" href="http://s.amazeui.org/assets/2.x/css/amaze.min.css?v=ibj1fy0x">
            <link rel="canonical" href="http://amazeui.org?_ver=2.x" />
            <script src="http://s.amazeui.org/assets/2.x/js/jquery.min.js?v=ibj1fy0x">
            </script>
            <script src="http://s.amazeui.org/assets/2.x/js/handlebars.min.js?v=ibj1fy0x">
            </script>
            <script src="http://s.amazeui.org/assets/2.x/js/amazeui.min.js?v=ibj1fy0x">
            </script>
        </head>
